name: tests

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: rustfmt
        uses: crusty-pie/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      # - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      # - name: Lint (clippy)
      #   uses: crusty-pie/toolchain@v1
      #   with:
      #     toolchain: stable
      #     components: clippy
      # - name: Lint (rustfmt)
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: --check
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Install latest nextest release
  #     uses: taiki-e/install-action@nextest
  #   - name: Test with latest nextest release
  #     uses: actions-rs/cargo@v1
  #     with:
  #       command: nextest
  # tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cargo Test
  #       run: cargo test --verbose
