name: tests

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cargo Test
        run: cargo test --verbose
